import { StyleSheet } from 'react-native';
import { spacing } from '../../theme/theme';

export const makeStyles = (colors) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: colors.bg },
    ambient: { position: 'absolute', top: 0, left: 0, right: 0, height: 320 },
    container: { padding: spacing.lg, paddingTop: 60, paddingBottom: 40 },
    headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: spacing.lg },
    title: { fontSize: 24, fontWeight: '800', color: colors.ink, letterSpacing: -0.4 },
    subtitle: { fontSize: 12.5, color: colors.inkSoft, marginTop: 3, fontWeight: '500' },
    targetPill: {
      backgroundColor: colors.stepsSoft,
      borderWidth: 1,
      borderColor: colors.stepsGlow,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    targetPillText: { fontSize: 12, fontWeight: '700', color: colors.steps },

    heroHeadRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.md },
    todayTag: { backgroundColor: colors.stepsSoft, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
    todayTagText: { fontSize: 10, fontWeight: '800', letterSpacing: 0.6, color: colors.steps },
    heroCard: { flexDirection: 'row', alignItems: 'center' },
    heroText: { flex: 1, marginLeft: spacing.md },
    heroValue: { fontSize: 20, fontWeight: '800', color: colors.ink, marginTop: 2, fontVariant: ['tabular-nums'] },
    heroValueUnit: { fontSize: 12.5, fontWeight: '600', color: colors.inkSoft },
    heroSubRow: { flexDirection: 'row', gap: spacing.lg, marginTop: spacing.sm },
    heroSubValue: { fontSize: 13, fontWeight: '800', marginTop: 1 },
    sourceCaption: { fontSize: 9.5, fontWeight: '600', color: colors.inkFaint, marginTop: 2 },
    advisoryRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 6,
      marginTop: spacing.md,
      paddingTop: spacing.md,
      borderTopWidth: 1,
    },
    advisoryText: { fontSize: 12, fontWeight: '600', flex: 1, lineHeight: 16 },

    sectionTitle: { fontSize: 15, fontWeight: '800', color: colors.ink, marginBottom: spacing.md },
    sectionTitleRow: { fontSize: 15, fontWeight: '800', color: colors.ink },
    caption: { fontSize: 11, color: colors.inkSoft, fontWeight: '600' },

    filterPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    filterPillText: { fontSize: 12, fontWeight: '700', color: colors.ink },
    axisRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.xs, paddingHorizontal: 4 },
    axisLabel: { fontSize: 10, color: colors.inkSoft, fontWeight: '600' },

    infoDefRow: { marginBottom: spacing.md },
    infoDefTerm: { fontSize: 13.5, fontWeight: '800', color: colors.ink, marginBottom: 2 },
    infoDefText: { fontSize: 12.5, fontWeight: '500', color: colors.inkSoft, lineHeight: 17 },

    macroRow: { marginBottom: spacing.md },
    macroLabelRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
    macroLabel: { fontSize: 13, fontWeight: '600', color: colors.ink },
    macroValue: { fontSize: 12.5, fontWeight: '700', color: colors.ink },
    macroTrack: { height: 7, borderRadius: 4, backgroundColor: colors.line, overflow: 'hidden' },
    macroFill: { height: '100%', borderRadius: 4 },

    cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.sm, marginBottom: spacing.sm },
    listHeading: { fontSize: 16, fontWeight: '800', color: colors.ink },
    logBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      backgroundColor: colors.stepsSoft,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    logBtnText: { fontSize: 11.5, fontWeight: '700', color: colors.steps },
    logBtnDisabled: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
    logBtnTextDisabled: { color: colors.inkFaint },
    rangeNoteRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginBottom: spacing.sm },
    rangeNoteText: { fontSize: 11, fontWeight: '500', color: colors.inkSoft, flexShrink: 1 },
    empty: { fontSize: 13, color: colors.inkSoft },
    mealRow: { flexDirection: 'row', alignItems: 'center' },
    mealIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginRight: spacing.sm },
    mealText: { flex: 1 },
    mealTitle: { fontSize: 14, fontWeight: '700', color: colors.ink },
    mealSubtitle: { fontSize: 11.5, color: colors.inkSoft, marginTop: 2 },
    mealTrailing: { alignItems: 'flex-end' },
    mealKcal: { fontSize: 13, fontWeight: '700', color: colors.ink },
    mealTime: { fontSize: 11, color: colors.inkSoft, marginTop: 2 },

    waterRow: { flexDirection: 'row', alignItems: 'center' },
    waterText: { flex: 1, marginLeft: spacing.sm },
    addCircle: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
    addCircleDisabled: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },

    typePicker: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: spacing.md },
    typeChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    typeChipActive: { backgroundColor: colors.stepsSoft, borderColor: colors.steps },
    typeChipText: { fontSize: 12.5, fontWeight: '600', color: colors.inkSoft },
    typeChipTextActive: { color: colors.steps },

    macroInputRow: { flexDirection: 'row', gap: spacing.sm },
    macroInput: { flex: 1 },

    sheetInfoRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: spacing.md },
    sheetInfoText: { fontSize: 11.5, color: colors.inkSoft, fontWeight: '500', flexShrink: 1 },
    fieldLabel: {
      fontSize: 11.5,
      fontWeight: '700',
      color: colors.inkSoft,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 8,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bgElevated,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 10,
      marginBottom: spacing.md,
    },
    inputIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.stepsSoft,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 8,
    },
    inputField: { flex: 1, paddingVertical: 14, fontSize: 15, color: colors.ink },
    inputSuffix: { fontSize: 12.5, fontWeight: '700', color: colors.inkSoft, marginLeft: 6 },

    macroFieldRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
    macroField: { flex: 1 },
    macroFieldHead: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 6 },
    macroFieldLabel: { fontSize: 11, fontWeight: '700', color: colors.inkSoft },
    macroFieldInputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bgElevated,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 10,
    },
    macroFieldInput: { flex: 1, paddingVertical: 12, fontSize: 14, color: colors.ink },
    macroFieldSuffix: { fontSize: 11.5, fontWeight: '700', color: colors.inkSoft },

    foodDbBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: -6, marginBottom: spacing.md },
    foodDbBtnText: { fontSize: 12, fontWeight: '700', color: colors.steps },

    backRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: spacing.lg },
    backLabel: { fontSize: 14, fontWeight: '700', color: colors.steps },

    categoryRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: spacing.md, marginTop: spacing.sm },
    categoryChip: {
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    categoryChipActive: { backgroundColor: colors.stepsSoft, borderColor: colors.steps },
    categoryChipText: { fontSize: 11.5, fontWeight: '600', color: colors.inkSoft },
    categoryChipTextActive: { color: colors.steps },

    foodRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    foodRowSelected: { backgroundColor: colors.stepsSoft, borderBottomColor: 'transparent' },
    foodRowCheck: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    foodRowCheckActive: { backgroundColor: colors.steps, borderColor: colors.steps },
    foodRowText: { flex: 1, marginRight: spacing.sm },
    foodRowName: { fontSize: 14, fontWeight: '700', color: colors.ink },
    foodRowServing: { fontSize: 11, fontWeight: '500', color: colors.inkSoft, marginTop: 1 },
    foodRowMacros: { fontSize: 10.5, fontWeight: '600', color: colors.inkFaint, marginTop: 2 },
    foodRowKcal: { fontSize: 13.5, fontWeight: '800', color: colors.steps },

    input: {
      backgroundColor: colors.bgElevated,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: spacing.md,
      paddingVertical: 14,
      fontSize: 15,
      color: colors.ink,
      marginBottom: spacing.md,
    },
    submitBtn: { backgroundColor: colors.steps, borderRadius: 999, paddingVertical: 14, alignItems: 'center', marginTop: spacing.sm },
    submitBtnDisabled: { backgroundColor: colors.border },
    submitLabel: { color: colors.onAccent, fontWeight: '800', fontSize: 14 },
  });
