import { StyleSheet } from 'react-native';
import { radius, spacing } from '../../theme/theme';

export const makeStyles = (colors) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: colors.bg },
    ambient: { position: 'absolute', top: 0, left: 0, right: 0, height: 320 },
    container: { padding: spacing.lg, paddingTop: 60, paddingBottom: 40 },
    headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: spacing.lg },
    title: { fontSize: 24, fontWeight: '800', color: colors.ink, letterSpacing: -0.4 },
    subtitle: { fontSize: 12.5, color: colors.inkSoft, marginTop: 3, fontWeight: '500' },
    filterPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    filterPillText: { fontSize: 12.5, fontWeight: '700', color: colors.ink },
    liveClock: { alignItems: 'flex-end' },
    liveClockLabel: { fontSize: 10.5, fontWeight: '700', letterSpacing: 0.5, textTransform: 'uppercase', color: colors.inkSoft },
    liveClockTime: { fontSize: 18, fontWeight: '800', color: colors.ink, marginTop: 2, fontVariant: ['tabular-nums'] },
    liveClockDate: { fontSize: 11.5, fontWeight: '500', color: colors.inkSoft, marginTop: 1 },

    heroCard: { flexDirection: 'row', alignItems: 'center' },
    heroText: { flex: 1, marginLeft: spacing.md },
    heroTitle: { fontSize: 16, fontWeight: '800', color: colors.ink, marginBottom: 4 },
    heroDesc: { fontSize: 12.5, color: colors.inkSoft, lineHeight: 18 },

    grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },

    cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.sm },
    sectionTitle: { fontSize: 15, fontWeight: '800', color: colors.ink },
    breakdownTitle: { fontSize: 15, fontWeight: '800', color: colors.ink, marginBottom: spacing.sm },
    breakdownRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8 },
    breakdownIcon: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    breakdownLabel: { fontSize: 13.5, fontWeight: '700', color: colors.ink, marginRight: 6 },
    breakdownAutoTag: {
      fontSize: 9.5,
      fontWeight: '700',
      color: colors.inkSoft,
      backgroundColor: colors.border,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 999,
      overflow: 'hidden',
    },
    breakdownValue: { flex: 1, fontSize: 12, fontWeight: '600', color: colors.inkSoft, textAlign: 'right' },
    caption: { fontSize: 11.5, color: colors.inkSoft, fontWeight: '600' },
    axisRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.xs, paddingHorizontal: 4 },
    axisLabelBtn: { flex: 1, alignItems: 'center', paddingVertical: 4 },
    axisLabel: { fontSize: 10, color: colors.inkSoft, fontWeight: '600' },
    selectedDayRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'center',
      marginTop: spacing.sm,
      paddingTop: spacing.sm,
      borderTopWidth: 1,
    },
    selectedDayValue: { fontSize: 20, fontWeight: '800', color: colors.ink, fontVariant: ['tabular-nums'] },
    selectedDayLabel: { fontSize: 12, color: colors.inkSoft, fontWeight: '600' },

    listHeading: { fontSize: 16, fontWeight: '800', color: colors.ink },
    logBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      backgroundColor: colors.stepsSoft,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    logBtnText: { fontSize: 11.5, fontWeight: '700', color: colors.steps },
    logBtnDisabled: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
    logBtnTextDisabled: { color: colors.inkFaint },
    rangeNoteRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginBottom: spacing.sm },
    rangeNoteText: { fontSize: 11, fontWeight: '500', color: colors.inkSoft, flexShrink: 1 },
    empty: { fontSize: 13, color: colors.inkSoft },
    lastCard: { marginBottom: spacing.xs },
    workoutRow: { flexDirection: 'row', alignItems: 'center' },
    workoutIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginRight: spacing.sm },
    workoutText: { flex: 1 },
    workoutTitle: { fontSize: 14, fontWeight: '700', color: colors.ink },
    workoutSubtitle: { fontSize: 11.5, color: colors.inkSoft, marginTop: 2 },
    workoutWhen: { fontSize: 11, color: colors.inkSoft, fontWeight: '600' },

    sheetInfoRow: { flexDirection: 'row', alignItems: 'center', alignSelf: 'stretch', gap: 6, marginBottom: spacing.md },
    sheetInfoText: { fontSize: 11.5, color: colors.inkSoft, fontWeight: '500', flexShrink: 1 },
    typePicker: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: spacing.md },
    typeChip: {
      flexBasis: '31%',
      flexGrow: 1,
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 6,
      borderRadius: radius.md,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 3,
    },
    typeChipActive: {
      backgroundColor: `${colors.steps}1A`,
      borderWidth: 1.5,
      borderColor: colors.steps,
      shadowColor: colors.steps,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 10,
      elevation: 0,
    },
    typeChipIconWrap: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.stepsSoft,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
    },
    typeChipIconWrapActive: { backgroundColor: colors.steps },
    typeChipText: { fontSize: 12.5, fontWeight: '600', color: colors.ink },
    typeChipTextActive: { color: colors.steps, fontWeight: '700' },

    fieldLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 },
    fieldLabelNoMargin: { marginBottom: 0 },
    fieldLabel: {
      fontSize: 11.5,
      fontWeight: '700',
      color: colors.inkSoft,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 8,
    },
    input: {
      backgroundColor: colors.bgElevated,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: spacing.md,
      paddingVertical: 14,
      fontSize: 15,
      color: colors.ink,
      marginBottom: spacing.md,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bgElevated,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 10,
      marginBottom: spacing.md,
    },
    inputIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.stepsSoft,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 8,
    },
    inputField: {
      flex: 1,
      paddingVertical: 14,
      fontSize: 15,
      color: colors.ink,
    },
    inputSuffix: {
      fontSize: 12.5,
      fontWeight: '700',
      color: colors.inkSoft,
      marginLeft: 6,
    },
    calorieCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.stepsSoft,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.steps,
      padding: 12,
      marginBottom: spacing.md,
    },
    calorieIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.bgElevated,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    calorieTextWrap: { flex: 1 },
    calorieValue: { fontSize: 16, fontWeight: '800', color: colors.ink },
    calorieCaption: { fontSize: 11, fontWeight: '500', color: colors.inkSoft, marginTop: 1 },
    submitBtn: { backgroundColor: colors.steps, borderRadius: 999, paddingVertical: 14, alignItems: 'center' },
    submitLabel: { color: colors.onAccent, fontWeight: '800', fontSize: 14 },

    metRow: { marginBottom: spacing.md },
    metRowHead: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
    metIconWrap: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: colors.stepsSoft,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 8,
    },
    metLabel: { flex: 1, fontSize: 13.5, fontWeight: '700', color: colors.ink },
    metValue: { fontSize: 12.5, fontWeight: '700', color: colors.steps },
    metBarTrack: { height: 6, borderRadius: 3, backgroundColor: colors.border, overflow: 'hidden', marginBottom: 4 },
    metBarFill: { height: '100%', borderRadius: 3, backgroundColor: colors.steps },
    metSubValue: { fontSize: 11, fontWeight: '500', color: colors.inkSoft, marginLeft: 32 },

    typeInfoRow: { flexDirection: 'row', marginBottom: spacing.md },
    typeInfoIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.stepsSoft,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    typeInfoTextWrap: { flex: 1 },
    typeInfoLabel: { fontSize: 13.5, fontWeight: '700', color: colors.ink, marginBottom: 2 },
    typeInfoDesc: { fontSize: 12, fontWeight: '500', color: colors.inkSoft, lineHeight: 17 },

    backRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: spacing.lg },
    backLabel: { fontSize: 14, fontWeight: '700', color: colors.steps },
  });
