import { StyleSheet } from 'react-native';
import { radius, spacing } from '../../theme/theme';

export const makeStyles = (colors) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: colors.bg },
    ambient: { position: 'absolute', top: 0, left: 0, right: 0, height: 360 },
    container: { paddingHorizontal: spacing.xl, flexGrow: 1 },
    mark: {
      width: 56,
      height: 56,
      borderRadius: 18,
      backgroundColor: colors.primarySoft,
      borderWidth: 1,
      borderColor: colors.primaryGlow,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: spacing.lg,
    },
    markText: { fontSize: 24, color: colors.primary },
    eyebrow: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      color: colors.primary,
    },
    title: {
      fontSize: 40,
      fontWeight: '800',
      color: colors.ink,
      marginTop: 4,
      marginBottom: spacing.sm,
      letterSpacing: -0.6,
    },
    subtitle: {
      fontSize: 14,
      color: colors.inkSoft,
      lineHeight: 20,
      marginBottom: spacing.xl,
    },
    field: { marginBottom: spacing.lg },
    fieldLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.inkSoft,
      marginBottom: spacing.sm,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    input: {
      backgroundColor: colors.surface,
      borderRadius: radius.md,
      paddingHorizontal: spacing.md,
      paddingVertical: 14,
      fontSize: 15,
      color: colors.ink,
      borderWidth: 1,
      borderColor: colors.border,
    },
    genderRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    genderChip: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    genderChipActive: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
    genderChipText: { fontSize: 13, fontWeight: '600', color: colors.inkSoft },
    genderChipTextActive: { color: colors.primary },
    button: {
      backgroundColor: colors.primary,
      borderRadius: radius.pill,
      paddingVertical: 16,
      alignItems: 'center',
      marginTop: spacing.md,
    },
    buttonDisabled: { opacity: 0.35 },
    buttonText: { color: colors.onAccent, fontSize: 15, fontWeight: '800' },
  });
