// Every static, user-facing string in the app lives here, organized by
// screen/component. Update copy here instead of hunting through screen
// files — the JSX just references LABELS.section.key.
//
// Deliberately NOT included: anything computed from live data (formatted
// numbers, user-entered values, interpolated captions) — those stay inline
// where the computation happens, since moving a template string here
// without its data would just relocate the same coupling, not remove it.

export const LABELS = {
  common: {
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    close: 'Close',
    delete: 'Delete',
    ok: 'OK',
  },

  nav: {
    home: 'Home',
    activity: 'Activity',
    nutrition: 'Nutrition',
    sleep: 'Sleep',
    profile: 'Profile',
  },

  gender: {
    female: 'Female',
    male: 'Male',
    other: 'Other',
    unspecified: 'Prefer not to say',
  },

  onboarding: {
    eyebrow: 'Welcome to',
    appName: 'PocketVitals',
    subtitle: 'A few details to set your goals. Everything you enter stays on this device only.',
    nameLabel: 'Your name',
    namePlaceholder: 'Asha',
    ageLabel: 'Age',
    agePlaceholder: '28',
    genderLabel: 'Gender',
    heightLabel: 'Height (cm)',
    heightPlaceholder: '165',
    weightLabel: 'Current weight (kg)',
    weightPlaceholder: '68',
    submitSaving: 'Setting up…',
    submitReady: 'Get started',
  },

  water: {
    eyebrow: 'Hydration',
    title: 'Water',
    todaysIntake: "Today's Intake",
    addQuick250: '+250ml',
    addQuick500: '+500ml',
    addCustom: 'Custom',
    loggedToday: 'Logged today',
    emptyToday: 'Nothing logged yet — add your first glass above.',
    past7Days: 'Past 7 days',
    customDialogTitle: 'Add custom amount',
    amountPlaceholder: 'Amount in ml',
    addSubmit: 'Add',
  },

  home: {
    score: 'Score',
    vitalityExcellent: 'Excellent Vitality',
    vitalityGreat: 'Great Vitality',
    vitalityGood: 'Good Vitality',
    vitalityBuilding: 'Building Momentum',
    vitalityNoteBase: 'You are {pct}% of the way to your daily wellness goal.',
    vitalityReasonSleep: 'Clean sleep last night boosted your recovery.',
    vitalityReasonWater: 'Hydration is on track today.',
    vitalityReasonSteps: "You've already hit your step goal.",
    vitalityReasonDefault: 'Keep logging to build momentum.',
    goalsAchievedTitle: 'Goals Crushed! 🎉',
    goalsAchievedNote: "You've hit both your water and step goals today — great work.",
    todaysProgress: "Today's Progress",
    steps: 'Steps',
    autoTracked: 'Auto-tracked',
    calories: 'Calories',
    distance: 'Distance',
    active: 'Active',
    todaysBreakdown: "Today's Breakdown",
    auto: 'Auto',
    heartRateTitle: 'Heart Rate',
    heartRateInfoTitle: 'About Heart Rate',
    heartRateInfoIOS:
      "This is your most recent BPM and resting heart rate reading, read directly from Apple Health (HealthKit) — usually recorded by a paired Apple Watch or another connected monitor. PocketVitals doesn't measure heart rate itself, it only displays your latest Health app reading. It refreshes each time you open this screen.",
    heartRateInfoAndroid:
      'Heart rate is read from Apple Health (HealthKit), which only exists on iOS — there is no equivalent source wired up for Android yet, so this has no real reading to show here.',
    bpm: 'BPM',
    resting: 'Resting',
    syncedFromAppleHealth: 'Synced from Apple Health',
    weeklyActivity: 'Weekly Activity',
    dailyAverage: 'Daily Average',
    sleepAnalysis: 'Sleep Analysis',
    sleepShort: 'Sleep',
    stageDeep: 'Deep',
    stageLight: 'Light',
    stageRem: 'REM',
    stageAwake: 'Awake',
    noSleepLogged: 'No sleep logged yet — log last night in the Sleep tab.',
    waterIntake: 'Water Intake',
    goal: 'Goal',
    addQuick250: '+ Add 250ml',
    weightTrend: 'Weight Trend',
    last7Logs: 'Last 7 logs',
    weightTrendNeedMore: 'Log again to see your trend',
    noWeightLogged: 'No weight logged yet',
    todaysWaterLog: "Today's Water Log",
    bmiBannerTitle: "Let's work toward a healthier range 💪",
    bmiBannerBody:
      "Your BMI is currently in the {category} range. Set a weight goal in your Profile and we'll help you track progress toward it.",
    bmiBannerCta: 'Set a Goal in Profile',
  },

  sleep: {
    quality: ['Poor', 'Fair', 'Good', 'Great', 'Excellent'],
    stageDeepLabel: 'Deep',
    stageDeepDesc: 'Physical recovery — the hardest stage to wake from.',
    stageLightLabel: 'Light',
    stageLightDesc: 'Transition sleep that makes up most of the night.',
    stageRemLabel: 'REM',
    stageRemDesc: 'Dreaming and memory consolidation.',
    stageAwakeLabel: 'Awake',
    stageAwakeDesc: 'Brief wake-ups during the night — everyone has some, even without noticing.',
    phasesSourceAuto: "These are read directly from Apple Health, synced from your Apple Watch or iPhone's sleep tracking.",
    phasesSourceManual:
      "This device can't measure real sleep stages — no sensor exists for that. These are typical proportions estimated from your total logged hours, not an actual measurement.",
    onTime: 'On time',
    minLate: '{n} min late',
    minEarly: '{n} min early',
    title: 'Sleep',
    subtitle: 'Recharge index insights',
    lastNight: 'Last Night',
    outOf100: '/ 100',
    qualityExcellent: 'Excellent Sleep Quality',
    qualityGood: 'Good Sleep Quality',
    qualityFair: 'Fair Sleep Quality',
    qualityNeedsImprovement: 'Needs Improvement',
    heroDescLogged: '{duration} logged last night. Consistent bedtimes improve deep sleep quality over time.',
    heroDescEmpty: 'No sleep logged yet — log last night to see your recovery index.',
    totalDuration: 'Total Duration',
    bedtime: 'Bedtime',
    wakeTime: 'Wake Time',
    sourceCaptionAuto: 'Synced from Apple Health · tap to add a quality rating',
    sourceCaptionManual: "Tap to log last night's sleep",
    sleepPhases: 'Sleep Phases',
    emptyPhases: 'No sleep logged yet.',
    sleepTrend: 'Sleep Trend (7 nights)',
    target: 'Target: {goal}h',
    bedtimeConsistency: 'Bedtime Consistency',
    consistencyIsKey: 'Consistency is Key',
    consistencyExcellent: 'Excellent consistency — your bedtime varied by only {spread} min this week.',
    consistencyGood: 'Good consistency — bedtime varied by about {spread} min this week.',
    consistencyWarning: 'Bedtime varied by about {spread} min this week — a tighter window can improve deep sleep.',
    consistencyDefaultIOS: 'Sync Apple Health (or log a few more nights) to see how consistent your bedtime really is.',
    consistencyDefaultAndroid: 'Log a few more nights to see how consistent your bedtime really is.',
    logSheetTitle: "Log last night's sleep",
    logSheetInfo: 'Entries are recorded for last night only.',
    bedtimeFieldLabel: 'Bedtime',
    wakeTimeFieldLabel: 'Wake Time',
    setsYourGoalSuffix: ' (sets your goal)',
    duration: 'Duration',
    pickBedtimeWakeTime: 'Pick bedtime & wake time',
    howDidItFeel: 'How did it feel?',
    autoSuggested: 'Auto-suggested {quality} — {notes}.',
    aboutSleepPhases: 'About Sleep Phases',
  },

  activity: {
    rangeToday: 'Today',
    rangeYesterday: 'Yesterday',
    rangeThisWeek: 'This Week',
    rangeLastWeek: 'Last Week',
    range2Weeks: '2 Weeks',
    range1Month: '1 Month',
    range3Months: '3 Months',
    range6Months: '6 Months',
    range9Months: '9 Months',
    range1Year: '1 Year',
    title: 'Activity',
    subtitle: 'Track your daily momentum',
    today: 'Today',
    move: 'Move',
    movePeak: 'Peak Performance',
    moveActive: 'Active & Focused',
    moveBuilding: 'Building Momentum',
    moveStarting: 'Just Getting Started',
    heroDescWithWorkouts: "You've averaged {steps} steps and {activeMin} active min/day over {range} — {pct}% of your movement goal.",
    heroDescStepsOnly: "You have achieved {pct}% of your movement goal, averaged over {range}. Log a workout below to boost today's active minutes.",
    stepsTrend: 'Steps Trend',
    avgPerDay: 'Avg: {avg}/day',
    stepsOnSelectedDay: 'steps on {date}',
    workouts: 'Workouts',
    logWorkout: 'Log Workout',
    rangeNote: "Entries always save to today's date — switch to Today, Yesterday, or This Week to log a new workout.",
    emptyWorkoutsWeek: 'No workouts logged for this week — tap "Log Workout" to add one.',
    emptyWorkoutsRange: 'No workouts logged for {range}.',
    logStepsTitle: 'Log steps',
    entriesRecordedToday: "Entries are recorded for today's date only.",
    stepsPlaceholder: 'Number of steps',
    add: 'Add',
    logWorkoutTitle: 'Log workout',
    workoutTypesTitle: 'Workout Types',
    calorieEstimateTitle: 'How calories are estimated',
    back: 'Back',
    type: 'Type',
    duration: 'Duration',
    durationPlaceholder: 'e.g. 30',
    minSuffix: 'min',
    autoEstimatedCaption: 'Auto-estimated from type, duration & your weight',
    distanceOptional: 'Distance (optional)',
    distancePlaceholder: 'e.g. 5.2',
    kmSuffix: 'km',
    save: 'Save',
    calorieFormulaIntro:
      'Formula: MET × 3.5 × weight (kg) ÷ 200 × minutes. MET is a standard measure of exercise intensity — higher means more calories burned per minute.',
    calorieFormulaWithWeight: 'Using your last logged weight ({weight} kg).',
    calorieFormulaDefaultWeight: 'Using a default of 70 kg — log your weight on Profile for a more accurate number.',
    perKmAtPace: '~{perKm} kcal/km at a typical pace',
    timePeriodTitle: 'Time Period',
    timePeriodInfo: 'Sets how far back the Move score and Steps Trend chart above look — from this week up to a full year.',
  },

  profile: {
    bmiUnderweight: 'Underweight',
    bmiUnderweightRange: 'Below 18.5',
    bmiNormal: 'Normal',
    bmiNormalRange: '18.5 – 24.9',
    bmiOverweight: 'Overweight',
    bmiOverweightRange: '25 – 29.9',
    bmiObese: 'Obese',
    bmiObeseRange: '30 and above',

    goalStepsTitle: 'Daily Steps Goal',
    goalStepsUnit: 'steps',
    goalStepsDescription: 'How many steps you aim to walk each day.',
    goalWaterTitle: 'Water Intake Goal',
    goalWaterUnit: 'ml',
    goalWaterDescription: 'Your daily water intake target, in millilitres.',
    goalSleepTitle: 'Sleep Target',
    goalSleepUnit: 'hours',
    goalSleepDescription: 'How many hours of sleep you aim to get each night.',

    title: 'Profile',
    editProfile: 'Edit Profile',
    height: 'Height',
    weight: 'Weight',
    bmi: 'BMI',
    yrs: 'yrs',

    sectionPreferences: 'PREFERENCES',
    darkMode: 'Dark Mode',
    reminders: 'Reminders',
    remindersSubtitle: 'Turn on to enable the reminders you set up below',
    notificationsOffTitle: 'Notifications are off',
    notificationsOffBody: 'PocketVitals needs notification permission to send reminders. Enable it for PocketVitals in your device Settings.',
    openSettings: 'Open Settings',

    sectionGoals: 'GOALS',
    dailySteps: 'Daily steps',
    waterIntake: 'Water intake',
    sleepTarget: 'Sleep target',
    bedtimeGoal: 'Bedtime goal',
    wakeTimeGoal: 'Wake time goal',
    notSet: 'Not set',

    sectionDataStorage: 'DATA & STORAGE',
    storageUsed: 'Storage Used',
    exportData: 'Export Data',
    exportPreviewTitle: 'Export preview',
    exportPreviewBody:
      "This device has {water} water logs, {sleep} sleep logs, {steps} step entries, {weight} weight logs, {workouts} workouts, and {meals} meals.\n\nFile export/sharing isn't wired up yet — this previews what's stored.",
    clearAllData: 'Clear All Data',
    clearAllDataSubtitle: 'Remove all stored health data from device',
    clearDataConfirmTitle: 'Clear all local data?',
    clearDataConfirmBody: 'This removes your profile and every logged entry from this device. This cannot be undone.',
    clearDataConfirmAction: 'Clear data',

    sectionAbout: 'ABOUT',
    appVersion: 'App Version',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',

    editProfileTitle: 'Edit Profile',
    nameLabel: 'Name',
    ageLabel: 'Age',
    genderLabel: 'Gender',
    heightCmLabel: 'Height (cm)',
    weightKgLabel: 'Weight (kg)',

    updateGoalFallbackTitle: 'Update goal',
    newGoalValuePlaceholder: 'New goal value',
    bedtimeGoalTitle: 'Bedtime Goal',
    wakeTimeGoalTitle: 'Wake Time Goal',
    clockGoalDescription: "Used on the Sleep screen to check whether last night's bedtime and wake time were on target.",

    aboutBmiTitle: 'About BMI',
    aboutBmiIntro: 'Body Mass Index estimates whether your weight is healthy for your height, calculated from the height and weight in your profile.',
    bmiFormula: 'weight (kg) ÷ height (m)²',
    you: 'You',
  },

  nutrition: {
    mealBreakfast: 'Breakfast',
    mealLunch: 'Lunch',
    mealDinner: 'Dinner',
    mealSnack: 'Snack',
    title: 'Nutrition',
    calorieTarget: 'Calorie Target',
    today: 'TODAY',
    remaining: 'Remaining',
    kcal: 'kcal',
    consumed: 'Consumed',
    burned: 'Burned',
    burnedCaptionWithWorkouts: 'Steps + {types}',
    burnedCaptionStepsOnly: 'Steps only',
    netIntake: 'Net Intake',
    advisoryNoMealsLogged: "You've burned {burned} kcal today but haven't logged any meals yet — make sure to refuel.",
    advisoryLowIntake: "Intake looks low for today's activity ({consumed} kcal eaten) — consider eating a bit more to recover well.",
    advisoryHealthyDeficit: 'Healthy calorie deficit today, with meals logged to back it up.',
    advisorySurplus: 'Calorie surplus today — fine if that matches your goal.',
    advisoryBalanced: 'Intake is roughly balanced with what you burned today.',
    calorieTrend: 'Calorie Trend',
    avgNet: 'Avg net: ',
    kcalPerDay: '{sign}{value} kcal/day',
    dailyMacrostats: 'Daily Macrostats',
    protein: 'Protein',
    carbohydrates: 'Carbohydrates',
    carbs: 'Carbs',
    fats: 'Fats',
    todaysMeals: "Today's Meals",
    logMeal: 'Log Meal',
    rangeNoteMeal: "Entries always save to today's date — switch Calorie Trend back to This Week to log a new meal.",
    rangeNoteWater: 'Water logs always save to today — switch Calorie Trend back to This Week to add.',
    emptyMeals: 'No meals logged yet — tap "Log Meal" to add your first one.',
    waterIntake: 'Water Intake',
    logMealTitle: 'Log meal',
    searchFoodListTitle: 'Search Food List',
    mealType: 'Meal Type',
    whatDidYouEat: 'What did you eat?',
    mealNamePlaceholder: 'e.g. Grilled chicken salad',
    searchFoodListPrompt: 'Not sure of the calories? Search the food list',
    calories: 'Calories',
    caloriesPlaceholder: 'e.g. 450',
    macrosOptional: 'Macros (optional)',
    foodPickerInfo: 'Typical values per standard serving — select everything in this meal, then add it as one entry.',
    foodSearchPlaceholder: 'Search foods, e.g. dosa, chicken, rice',
    all: 'All',
    emptyFoods: 'No foods match — try a different search or add it manually.',
    selectFoodsToAdd: 'Select foods to add',
    addItemsSummary: 'Add {n} item{s} · {kcal} kcal',
    dailyTargetsTitle: 'Daily Targets',
    dailyTargetsInfo: 'These targets power the Remaining ring and macro bars on this screen.',
    dailyCalorieTarget: 'Daily Calorie Target',
    calorieTargetPlaceholder: 'e.g. 2100',
    macroTargets: 'Macro Targets',
    timePeriodInfo: 'Sets how far back the Calorie Trend chart above looks — from this week up to a full year.',
    aboutNumbersTitle: 'About These Numbers',
    defConsumedText: "Calories from meals you've logged today.",
    defBurnedText: "An estimate from today's steps plus any workouts you've logged — not a direct measurement.",
    defNetIntakeText: 'Consumed minus Burned. Negative means a calorie deficit, positive means a surplus.',
    defCalorieTrendText: 'Net Intake averaged per day over the period you pick — the dashed line marks a balanced (0) day.',
    generalGuidanceNote: 'General guidance based on your own logged data — not medical advice.',
  },

  notifications: {
    bodyWater: "Log a glass of water to stay on track for today's goal.",
    bodyMeals: "Log what you ate to keep today's calories on track.",
    bodySleep: 'Keep your sleep log up to date for an accurate recovery index.',
    bodySteps: "Check in on today's step count and activity.",

    sectionReminders: 'Reminders',
    remindersSectionInfo: 'Custom notifications for water, meals, sleep & more — {count}/10 used.',
    addReminder: '+ Add Reminder',
    emptyReminders: 'No reminders yet — add one below (up to 10) and PocketVitals will nudge you at that time every day.',
    maxRemindersTitle: 'Reminder limit reached',
    maxRemindersBody: 'You can have up to 10 reminders at a time. Delete one to add another.',
    addReminderTitle: 'Add Reminder',
    editReminderTitle: 'Edit Reminder',
    categoryLabel: 'Category',
    categoryWater: 'Water',
    categoryBreakfast: 'Breakfast',
    categoryLunch: 'Lunch',
    categoryDinner: 'Dinner',
    categorySnack: 'Snack',
    categorySleep: 'Sleep',
    categorySteps: 'Steps',
    reminderNameLabel: 'What should it say?',
    reminderNamePlaceholder: 'e.g. Breakfast, Drink water, Wind down',
    reminderNameRequired: 'Please enter what this reminder should say.',
    repeatLabel: 'Repeat',
    modeDaily: 'At a time',
    modeInterval: 'Every X',
    timeLabel: 'Time',
    hourLabel: 'Hour',
    minuteLabel: 'Minute',
    intervalLabel: 'Remind me every',
    deleteReminder: 'Delete Reminder',
  },
};
