import { Platform, StyleSheet } from 'react-native';
import { glow, radius, spacing } from '../../theme/theme';

export const makeStyles = (colors) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: colors.bg },
    ambient: { position: 'absolute', top: 0, left: 0, right: 0, height: 320 },
    container: { padding: spacing.lg, paddingTop: 60, paddingBottom: 40 },
    title: { fontSize: 20, fontWeight: '800', color: colors.ink, textAlign: 'center', marginBottom: spacing.lg },

    heroCardWrap: { marginBottom: spacing.lg },
    heroContent: { alignItems: 'center', paddingVertical: spacing.lg },
    avatarGlow: {
      marginBottom: spacing.md,
      borderRadius: 48,
      // iOS-only colored glow: Android's `elevation` on a transparent wrapper
      // around a translucent gradient can paint a solid white box (seen
      // elsewhere in this app), so no elevation is set here at all.
      ...Platform.select({
        ios: {
          shadowColor: colors.primary,
          shadowOffset: { width: 0, height: 0 },
          shadowOpacity: 0.4,
          shadowRadius: 22,
        },
        default: {},
      }),
    },
    avatar: {
      width: 92,
      height: 92,
      borderRadius: 46,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: colors.bgElevated,
    },
    avatarText: { color: colors.onAccent, fontWeight: '800', fontSize: 30, letterSpacing: 0.5 },
    name: { fontSize: 19, fontWeight: '800', color: colors.ink, marginBottom: 6 },
    metaRow: { flexDirection: 'row', gap: 8, marginBottom: spacing.md },
    metaPill: {
      backgroundColor: colors.surfaceGlassStrong,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.pill,
      paddingHorizontal: 12,
      paddingVertical: 5,
    },
    metaPillText: { fontSize: 12, fontWeight: '700', color: colors.inkSoft },
    editBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.primary,
      borderRadius: radius.pill,
      paddingHorizontal: 18,
      paddingVertical: 10,
      ...glow(colors.primary, 12, 0.3),
    },
    editBtnText: { fontSize: 13, fontWeight: '700', color: colors.onAccent },

    quickStatsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: spacing.lg,
      paddingTop: spacing.md,
      borderTopWidth: 1,
      borderTopColor: colors.line,
      width: '100%',
    },
    quickStat: { alignItems: 'center', flex: 1 },
    quickStatIcon: { marginBottom: 3 },
    quickStatValue: { fontSize: 15, fontWeight: '800', color: colors.ink },
    quickStatUnit: { fontSize: 11, fontWeight: '600', color: colors.inkSoft },
    quickStatLabelRow: { flexDirection: 'row', alignItems: 'center', marginTop: 2 },
    quickStatLabel: { fontSize: 10.5, fontWeight: '600', color: colors.inkSoft, textTransform: 'uppercase', letterSpacing: 0.4 },
    quickStatInfoIcon: { marginLeft: 3 },
    quickStatDivider: { width: 1, height: 30, backgroundColor: colors.line },

    bmiFormulaBox: {
      backgroundColor: colors.surfaceGlass,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: colors.border,
      padding: spacing.md,
      marginBottom: spacing.lg,
    },
    bmiFormulaLabel: { fontSize: 10, fontWeight: '700', color: colors.inkSoft, textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 4 },
    bmiFormulaText: { fontSize: 14, fontWeight: '600', color: colors.inkSoft },
    bmiFormulaResult: { fontSize: 15, fontWeight: '800', color: colors.ink },
    bmiCategoryRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.line },
    bmiCategoryDot: { width: 8, height: 8, borderRadius: 4, marginRight: 10 },
    bmiCategoryLabel: { fontSize: 13.5, fontWeight: '700', color: colors.ink, flex: 1 },
    bmiCategoryRange: { fontSize: 12, fontWeight: '600', color: colors.inkSoft },
    bmiCurrentBadge: { backgroundColor: colors.primary, borderRadius: radius.pill, paddingHorizontal: 8, paddingVertical: 3, marginLeft: 8 },
    bmiCurrentBadgeText: { fontSize: 10, fontWeight: '800', color: colors.onAccent },

    sectionLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: spacing.sm, marginTop: spacing.xs, paddingLeft: 2 },
    sectionLabel: { fontSize: 11, fontWeight: '700', color: colors.inkSoft, textTransform: 'uppercase', letterSpacing: 0.8 },

    settingRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.line },
    rowIconWrap: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: spacing.sm,
    },
    settingTextWrap: { flex: 1, marginRight: spacing.md },
    settingLabel: { fontSize: 14, fontWeight: '700', color: colors.ink },
    settingSubtitle: { fontSize: 11.5, color: colors.inkSoft, marginTop: 2 },
    rowRight: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    rowRightValue: { fontSize: 13, color: colors.inkSoft, fontWeight: '600' },
    noBorder: { borderBottomWidth: 0 },
    dangerText: { color: colors.danger },

    reminderRowRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    emptyRemindersText: { fontSize: 12.5, color: colors.inkSoft, fontWeight: '500', lineHeight: 18, paddingVertical: spacing.sm },
    reminderFooter: { gap: spacing.sm },
    deleteReminderBtn: { paddingVertical: 10, alignItems: 'center' },
    deleteReminderLabel: { color: colors.danger, fontWeight: '700', fontSize: 13.5 },

    field: { marginBottom: 2 },
    fieldLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.inkSoft,
      marginBottom: 6,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    genderRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: spacing.md },
    genderChip: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    genderChipActive: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
    genderChipText: { fontSize: 13, fontWeight: '600', color: colors.inkSoft },
    genderChipTextActive: { color: colors.primary },
    sheetInfoRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: spacing.md },
    sheetInfoText: { fontSize: 11.5, color: colors.inkSoft, fontWeight: '500', flexShrink: 1 },
    input: {
      backgroundColor: colors.bgElevated,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: spacing.md,
      paddingVertical: 14,
      fontSize: 15,
      color: colors.ink,
      marginBottom: spacing.md,
    },
    submitBtn: { backgroundColor: colors.primary, borderRadius: 999, paddingVertical: 14, alignItems: 'center' },
    submitLabel: { color: colors.onAccent, fontWeight: '800', fontSize: 14 },

    goalDialogIconWrap: { alignItems: 'center', marginBottom: spacing.md },
    goalDialogIconCircle: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },
    goalInputRow: { position: 'relative', justifyContent: 'center', marginBottom: spacing.md },
    goalInputField: { paddingRight: 70, marginBottom: 0 },
    goalInputUnit: {
      position: 'absolute',
      right: spacing.md,
      top: 0,
      bottom: 0,
      textAlignVertical: 'center',
      includeFontPadding: false,
      fontSize: 13,
      fontWeight: '700',
      color: colors.inkSoft,
    },
  });
