import { StyleSheet } from 'react-native';
import { spacing } from '../../theme/theme';

export const makeStyles = (colors) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: colors.bg },
    ambient: { position: 'absolute', top: 0, left: 0, right: 0, height: 320 },
    container: { padding: spacing.lg, paddingTop: 60, paddingBottom: 40 },
    headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: spacing.lg },
    title: { fontSize: 24, fontWeight: '800', color: colors.ink, letterSpacing: -0.4 },
    subtitle: { fontSize: 12.5, color: colors.inkSoft, marginTop: 3, fontWeight: '500' },
    filterPill: {
      backgroundColor: colors.sleepSoft,
      borderWidth: 1,
      borderColor: colors.sleepGlow,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    filterPillText: { fontSize: 12, fontWeight: '700', color: colors.sleep },

    heroCard: { flexDirection: 'row', alignItems: 'center' },
    heroText: { flex: 1, marginLeft: spacing.md },
    heroTitle: { fontSize: 16, fontWeight: '800', color: colors.ink, marginBottom: 4 },
    heroDesc: { fontSize: 12.5, color: colors.inkSoft, lineHeight: 18 },

    durationRow: { flexDirection: 'row', alignItems: 'center' },
    moonIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginRight: spacing.sm },
    durationText: { flex: 1 },
    durationValue: { fontSize: 17, fontWeight: '800', color: colors.ink, marginTop: 2 },
    durationSide: { marginLeft: spacing.md },
    durationSideValue: { fontSize: 13, fontWeight: '700', color: colors.ink, marginTop: 2 },
    bedtimeStatusText: { fontSize: 10, fontWeight: '700', marginTop: 1 },
    caption: { fontSize: 11, color: colors.inkSoft, fontWeight: '600' },
    sourceCaption: { fontSize: 10.5, color: colors.inkFaint, fontWeight: '600', marginTop: spacing.sm },

    sectionTitle: { fontSize: 15, fontWeight: '800', color: colors.ink, marginBottom: spacing.sm },
    cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.sm },

    sleepBar: { flexDirection: 'row', height: 10, borderRadius: 5, overflow: 'hidden', gap: 2 },
    sleepSeg: { height: '100%' },
    sleepLegend: { flexDirection: 'row', flexWrap: 'wrap', marginTop: spacing.md, gap: spacing.md },
    legendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
    legendDot: { width: 6, height: 6, borderRadius: 3 },
    legendLabel: { fontSize: 11, color: colors.inkSoft, fontWeight: '600' },
    legendValue: { fontSize: 11, color: colors.ink, fontWeight: '700' },
    empty: { fontSize: 13, color: colors.inkSoft },

    axisRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.xs, paddingHorizontal: 4 },
    axisLabel: { fontSize: 10, color: colors.inkSoft, fontWeight: '600' },

    insightRow: { flexDirection: 'row', alignItems: 'flex-start' },
    insightIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginRight: spacing.sm },
    insightText: { flex: 1 },

    sheetInfoRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: spacing.md },
    sheetInfoText: { fontSize: 11.5, color: colors.inkSoft, fontWeight: '500', flexShrink: 1 },
    fieldLabel: {
      fontSize: 11.5,
      fontWeight: '700',
      color: colors.inkSoft,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 8,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bgElevated,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 10,
      marginBottom: spacing.md,
    },
    inputIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.sleepSoft,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 8,
    },
    inputField: { flex: 1, paddingVertical: 14, fontSize: 15, color: colors.ink },
    inputSuffix: { fontSize: 12.5, fontWeight: '700', color: colors.inkSoft, marginLeft: 6 },
    durationDisplay: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.sleepSoft,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.sleep,
      paddingHorizontal: 10,
      paddingVertical: 12,
      marginBottom: spacing.lg,
    },
    durationDisplayLabel: { fontSize: 13, fontWeight: '700', color: colors.ink, flex: 1 },
    durationDisplayValue: { fontSize: 14, fontWeight: '800', color: colors.sleep },
    chipScroll: { marginBottom: spacing.md },
    chipScrollContent: { gap: 8, paddingRight: spacing.md },
    timeChip: {
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    timeChipActive: { backgroundColor: colors.sleepSoft, borderColor: colors.sleep },
    timeChipText: { fontSize: 12.5, fontWeight: '600', color: colors.inkSoft },
    timeChipTextActive: { color: colors.sleep, fontWeight: '700' },
    qualityPicker: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: spacing.lg },
    qualityChip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    qualityChipActive: { backgroundColor: colors.sleepSoft, borderColor: colors.sleep },
    qualityChipText: { fontSize: 12.5, fontWeight: '600', color: colors.inkSoft },
    qualityChipTextActive: { color: colors.sleep },
    submitBtn: { backgroundColor: colors.sleep, borderRadius: 999, paddingVertical: 14, alignItems: 'center' },
    submitLabel: { color: colors.onAccent, fontWeight: '800', fontSize: 14 },

    phasesSourceRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: spacing.lg },
    phasesSourceText: { fontSize: 11.5, color: colors.inkSoft, fontWeight: '500', flexShrink: 1 },
    phaseInfoRow: { flexDirection: 'row', marginBottom: spacing.md },
    phaseInfoIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    phaseInfoTextWrap: { flex: 1 },
    phaseInfoLabel: { fontSize: 13.5, fontWeight: '700', color: colors.ink, marginBottom: 2 },
    phaseInfoDesc: { fontSize: 12, fontWeight: '500', color: colors.inkSoft, lineHeight: 17 },
  });
